services:
  lab-framework:
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  redis:
    build:
      dockerfile: ./Dockerfile.redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local

networks:
  default:
    name: lab-framework
    driver: bridge
